name: 'Lint'

on:
  push:
    branches: [develop]
  pull_request:
    branches: [master, develop]

jobs:
  lint:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v3.5.3'

      - name: 'Setup Node.js'
        uses: 'actions/setup-node@v3.6.0'
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: 'Install dependencies'
        run: 'npm clean-install'

      - run: 'npm run lint:commit -- --to "${{ github.sha }}"'
      - run: 'npm run lint:editorconfig'
      - run: 'npm run lint:markdown'
      - run: 'npm run lint:eslint'
      - run: 'npm run lint:prettier'
