name: 'Release'

on:
  push:
    branches: [master]

jobs:
  release:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'

      - name: 'Use Node.js'
        uses: 'actions/setup-node@v2.3.0'
        with:
          node-version: '16.x'
          cache: 'npm'

      - name: 'Install'
        run: 'npm install'

      - name: 'Build Package'
        run: 'npm run build'

      - name: 'Release'
        run: 'npm run release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
